<%@ taglib uri="http://wurfl.sourceforge.net/wng" prefix="wng"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<wng:document>
	<wng:head>
		<wng:title text="Spring Mobile | Wurfl Showcase | WNG" />
		<wng:meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<wng:meta httpEquiv="Cache-Control" content="no-cache" />
		<wng:css_style>
			<wng:css selector="body">
				<wng:css_property name="margin" value="0" />
				<wng:css_property name="border" value="0" />
				<wng:css_property name="font-family" value="arial, sans-serif" />
			</wng:css>
			<wng:css selector="a">
				<wng:css_property name="color" value="#696" />
				<wng:css_property name="font-weight" value="bold" />
				<wng:css_property name="text-decoration" value="none" />
			</wng:css>
		</wng:css_style>
	</wng:head>
	<wng:body>
		<wng:title
			text="Hello mobile user! Here's a page generated by WNG for you." align="center" text_color="#fff" background_color="#369">
			<wng:css>
				<wng:css_property name="font-size" value="18px" />
				<wng:css_property name="font-weight" value="bold" />
			</wng:css>
		</wng:title>
		<wng:navigation_bar separator=" | ">
			<wng:css>
				<wng:css_property name="font-size" value="12px" />
				<wng:css_property name="margin-left" value="12px" />
				<wng:css_property name="padding-top" value="4px" />
			</wng:css>
			<wng:link href="${pageContext.request.contextPath}/wng?UA=iPhone" text="Try iPhone (XHTML Advanced Grade)" />
			<wng:link href="${pageContext.request.contextPath}/wng?UA=Blackberry" text="Try Blackberry (XHTML Simple Grade)" />
			<wng:link href="${pageContext.request.contextPath}" text="Home" />
		</wng:navigation_bar>
	</wng:body>
</wng:document>