/*
 * Copyright 2010 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.showcases.wurfl;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.mobile.device.Device;
import org.springframework.mobile.device.mvc.DeviceWebArgumentResolver;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Handles requests for the spring-mobile showcase.
 * @author Keith Donald
 */
@Controller
public class WurflShowcaseController {

	private Logger logger = LoggerFactory.getLogger(WurflShowcaseController.class);
	
	/**
	 * Show the home page to the user.
	 * Declares a {@link Device} parameter to show how you can resolve a model for the device that originated the current request.
	 * Argument resolution is handled by the {@link DeviceWebArgumentResolver} installed by {@link WebArgumentResolverInstaller}.
	 */
	@RequestMapping("/")
	public String home(Device device) {
		logger.info("Home page request originated from " + device);
		return "home";
	}
	
	/**
	 * Show the home page to the user.
	 * Declares a {@link Device} parameter to show how you can resolve a model for the device that originated the current request.
	 * Argument resolution is handled by the {@link DeviceWebArgumentResolver} installed by {@link WebArgumentResolverInstaller}.
	 */
	@RequestMapping("/mobile")
	public String mobile(Device device) {
		if (!device.isMobile()) {
			logger.info("Non-mobile device attempted to access the /mobile site; redirecting to standard site");
			return "redirect:/";
		}
		logger.info("Mobile request originated from " + device);
		return "mobile";
	}

	/**
	 * Show a page generated by WNG to the user.
	 * The page will automatically render in format that's graded as the optimal format for the user's device (e.g. WML, XHTML Simple, XHTML Advanced).
	 */
	@RequestMapping("/mobile/wng")
	public String wng(Device device) {
		if (!device.isMobile()) {
			logger.info("Non-mobile device attempted to access the /mobile site; redirecting to standard site");
			return "redirect:/";
		}
		return "wng";
	}

}